title: Sucro Portfolio
author: Suzan Sucro
author_title: Web Developer
email: your-email@domain.com
description: > # Personal portfolio site for Suzan Sucro.
baseurl: ""
url: "suzmas.com"

twitter_url: https://twitter.com/suzanmsu
linkedin_url: https://www.linkedin.com/in/suzan-sucro-55451a48/
github_url: https://github.com/suzmas

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

sass:
  sass_dir: _sass
  style: compressed
